# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs/apt"
      ref: "10.0.0"
    concat: "puppetlabs/concat"
    stdlib: "puppetlabs/stdlib"
    systemd: "puppet/systemd"
    yumrepo_core: "puppetlabs/yumrepo_core"
